site_name: EOLib
site_description: Core library for writing applications related to Endless Online.
site_author: Jonah Jeleniewski
site_url: https://cirras.github.io/eolib-python/
repo_url: https://github.com/Cirras/eolib-python/
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  custom_dir: docs/overrides
  features:
    - navigation.instant
    - search.suggest
    - navigation.sections
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
extra:
  version:
    provider: mike
extra_css:
  - stylesheets/extra.css
nav:
- Home: index.md
- API Reference: reference/
plugins:
- search
- mike:
    canonical_version: latest
- gen-files:
    scripts:
      - docs/gen_ref_pages.py
- literate-nav
- section-index
- include-markdown
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [src]
        options:
          members_order: source
          show_if_no_docstring: true
          summary: true
          filters: ["!^_[^_]", "!^__repr__$", "!^__all__$"]
markdown_extensions:
  - admonition
  - attr_list